### ISSUE TITLE
cm-14.1 Nougat 

### ISSUE THREAD

**Issue by Micha-Btz** [cm12-amami/discussion#31]
Hey,
 
I have started yesterday the setup for cm-14.1. The plan is that we merge the branches from aicp n7.1 to our repo's and use the main source from LOS for cm-14.1. The goal is to get a working Nougat for our devices with less work in backporting patches.
Since aicp are build working roms so we should also be able to do so.

schedule:

- [x] setup amami repo for cm-14.1
- [x] merge kernel branch n7.1 - at start unsing kernel directly from aicp 
- [x] merge rhine-common branch n7.1
- [x] merge msm8974-common branch n7.1

I will create the branches for this and will push a local mainfest to our repo.

Thoughts, comments?

**Comment by hahnjo** [comment]
IMO this is really out of scope of what we set out to do: Maintaining a working custom ROM, which is also reflected by the name `cm12-amami`. To be honest I don't think it's worth the effort to port a newer version of Android to phone more than 4 years old. I will probably buy a new one throughout the year...

**Comment by Micha-Btz** [comment]
@hahnjo 
You are absolutely right. We will create cm12-amami and as long as my phone live, we can do this.

But as always there is one thing I want to have for long time. Adoptable storage, since my internal memory is always full. So, when I have time and cm-12-amami need's no attention I will give it a try. If it will not work, so I have just learned a lot about git merges.

**Comment by Micha-Btz** [comment]
build run fine with the manifest installation test will be the next days, after doing some backups.

**Comment by Micha-Btz** [comment]
I use the rom since last Wednesday without problems. No reboot or crash.

- [x] GPS
- [x] mobile connections
- [x] phone call
- [x] bluetooth
- [x] adoptable storage
- [x] SMS/MMS
- [x] Photos / Videorecording

All this works. The only thing I have to test is encryption. If you want to give it a try, I have upload it here https://www.androidfilehost.com/?fid=673956719939837413
The camera from LOS have a little trouble, if you change pic resolution the app became black and unusable, but with open camera from f-droid the it works well. The picture quality is quite as good as on stock rom.

@MSe1969 What's  your opinion on this?

**Comment by Micha-Btz** [comment]
![screenshot_20180428-113236](https://user-images.githubusercontent.com/4420944/39394925-270ed5ec-4ad8-11e8-9de0-6351cb544464.png)

**Comment by MSe1969** [comment]
I have successfully built myself, but decryption did not work. My device is encrypted and I did not want to format my data partition to avoid trouble with my LOS 12 backup.

**Comment by MSe1969** [comment]
When I find some time, I'll have a look at the device config...

**Comment by MSe1969** [comment]
Haven't found any obvious things like fstab.qcom with regards to the encryption issue (I am however not really experienced when it comes to properly configure a device) - we may have to look for a working device config... 
Nevertheless, I have noticed something else, which I don't really like: permissive SELinux (this is fine for testing, but not really suitable as a daily driver). So if we really find a working rhine/amami device config for encryption, which also brings along a solid sepolicy allowing to boot in strict SELinux mode, I'd be happy to switch to N; if not, I'll be happy to test and research, but really see our LP version a solid reason to continue.

**Comment by Micha-Btz** [comment]
I think there are some differences in  partition layout. I have had to delete and recreate data partition. Otherwise the rom doesn't boot complete.

SElinux in enforce mode works, but there are some errors. 
https://gist.github.com/Micha-Btz/d49bad46a1321f7edb559572291dc5a8

**Comment by Micha-Btz** [comment]
Some denails I have fixed but this is WIP. I have added a separate file for now.

**Comment by Micha-Btz** [comment]
so mobile data works now with selinux enforce - looks good to me :-)

@MSe1969 
Your problem is that you can't enctrpyt your data partition while the nougat rom is booting, did I understand it right?
As far as I remember the problem is there since the first roms. Can you try to get a log?

**Comment by MSe1969** [comment]
@Micha-Btz - correct.

What I did was to wipe (factory reset + system) after a backup in TWRP, but I did not format the /data partition (which is the default behavior of TWRP to keep the internal memory and the encryption intact). During boot, when I get to the point to enter my decryption password, I receive the notification, that my password is correct, but the /data partition seems corrupted. Restoring my cm-12.1-backup made everything work again.

That means either, that the encryption config is not correct or, that N encrypts differently and thus a physical formatting to get rid of the L encryption is necessary to continue...

I know that I can try overcoming my issue by **physically formatting** the /data partition in TWRP (to get rid of the encryption), but I fear that in that case, I may not be able to restore my previous cm-12.1 backup later. (And I would need to backup my internal memory in addition - but that is only a side aspect) 
My fear may however be wrong - do you maybe have any insight here? I am not sure whether TWRP creates a 'low-level' binary-type backup image or simply copies each file and related attributes logically from the decrypted partition. The latter of course would be preferrable and more robust, but I don't want to find out the hard way :)

With regards to getting a log: 
Not sure whether at that early stage adb would work already; but besides - we have a classical "catch-22": 
- 1st boot after a wipe/factory reset means adb is switched off and you can't connect via USB
- once I would have solved the issue and enable adb, I won't be faced with the issue, because I would have already successfully booted and launched the OS...

**Comment by MSe1969** [comment]
@Micha-Btz : Two comment to your SELinux fixes
1. Good idea to temporarily collect the additional stuff in an extra file - however, once we have solved the SELinux policy, the updated rules should be added to the respective domain files.
2. I don't like the 'untrusted_app' rules - normally, 'untrusted_app' refers to all user apps, so a 'naked' ROM installed after a factory reset should not trigger any 'unstrusted_app' denials. The only exception to this was CMFileManager (which is meanwhile deprecated in cm-14.1), because only 'unstrusted_app' is allowed to invoke root (CMFileManager therefore had an own re-classification in mac_permissions.xml). 
I assume that you perform your test with your specific user apps installed and not with a 'naked' ROM (which makes sense), but your added 'unstrusted_app' rules seem to 'fix' denials, which should be in place to simply tell user-installed apps to mind their own business...

**Comment by Micha-Btz** [comment]
I don't know if it is really possible to encrypt a lollipop data partition with the nougat rom. Seems that we will have to evaluate this first. Maybe we should ask this in LOS dev irc to get to know.

That was the plan for SELinux. After it works I will move this to the special file. I have had no problems with my rom. The untrusted_app rules are dedicated to the afwall start script. there is a fix for SELinux in the latest afwall release from yesterday. Will take a look if it is ok now. So this rules will be deleted.
I think the only fix we are really need is the rild fix, because for the first rom with enforce mode the mobile data was not working.

**Comment by Micha-Btz** [comment]
As far as I know trwp makes a file backup with zip and you can always restore it.
As test you can unpack an archive.
 https://www.semipol.de/2016/07/30/android-restoring-apps-from-twrp-backup.html

**Comment by MSe1969** [comment]
Thanks for the info. I'll do another build then and will format my data partition this time, if needed :) - will before try to find out about LP encryption

**Comment by MSe1969** [comment]
**Good news** with regards to encryption:
- I have formatted /data and afterwards, I was able to boot cm-14.1
- Afterwards, I have successfully encrypted my device under cm-14.1 
- set PIN as boot-up and lockscreen password, reboots into TWRP and OS OK
- Then I installed 'snooper-stopper' and set a different boot vs. lockscreen password
- again, reboots into OS and TWRP OK
- Did an interim backup in TWRP of my cm-14.1 build
- Next, I was even able to restore and boot-up my cm-12.1 backup without any encryption issues
- Finally, I have restored my cm-14.1 backup and again, decryption worked

**Comment by MSe1969** [comment]
Some slightly 'negative' observations:
- After entering the decryption password during boot, the screen simply turns black, no boot animation; you have to wait some time and when you then press the power button, you can enter the SIM PIN.
- Very first boot-up (after having formatted /data, see above) caused SetupWizard to hang, had to reboot, but then it worked

**Comment by MSe1969** [comment]
Next homework: **KERNEL**
SuperLamic's kernel is a little outdated and misses important ASB patches. An automatic merge of our kernel source does not work. I see the following options, how to proceed here:
- use the AICP 'o8.1' branch, which is kept up to date (will try that now)
- 'Slave work' variant no.1: Manually apply the ASB patches since August 2017
- 'Slave work' variant no.2: List our commit hashes since August 2017 (git log --format...) and cherry-pick them one-by-one...

In case no.1 does not work, any further ideas of avoiding the 'slave work' ?

**Comment by MSe1969** [comment]
hmmm... the o8.1 AICP kernel works (and the boot animation issue described above does not happen any longer), however - the kernel's meta data still shows 3.4.0, which somehow tells me that the original 3.4. linux kernel sources were not completely merged...
What is your opinion how to proceed with the kernel?
@Micha-Btz I see you have copied the cm-12.1 branch of our kernel into a cm-14.1 branch - have you tried already a build which simply uses our kernel sources?

**Comment by Micha-Btz** [comment]
which twrp version do you use?

Am 4. Mai 2018 18:25:42 MESZ schrieb MSe1969 <notifications@github.com>:
>**Good news** with regards to encryption:
>- I have formatted /data and afterwards, I was able to boot cm-14.1
>- Afterwards, I have successfully encrypted my device under cm-14.1 
>- set PIN as boot-up and lockscreen password, reboots into TWRP and OS
>OK
>- Then I installed 'snooper-stopper' and set a different boot vs.
>lockscreen password
>- again, reboots into OS and TWRP OK
>- Did an interim backup in TWRP of my cm-14.1 build
>- Next, I was even able to restore and boot-up my cm-12.1 backup
>without any encryption issues
>- Finally, I have restored my cm-14.1 backup and again, decryption
>worked

**Comment by Micha-Btz** [comment]
the kernel is one thing I have thought about some days. Merge the aicp is not possible there are more than 700 conflicts.
As our kernel is in a really good condition, I think it would be the best to pick the patches to our kernel.

for the cm-14.1 branch we need some patches to make it compatible with LOS.
So just build will not work.

Am 4. Mai 2018 18:40:34 MESZ schrieb MSe1969 <notifications@github.com>:
>Next homework: **KERNEL**
>SuperLamic's kernel is a little outdated and misses important ASB
>patches. An automatic merge of our kernel source does not work. I see
>the following options, how to proceed here:
>- use the AICP 'o8.1' branch, which is kept up to date (will try that
>now)
>- 'Slave work' variant no.1: Manually apply the ASB patches since
>August 2017
>- 'Slave work' variant no.2: List our commit hashes since August 2017
>(git log --format...) and cherry-pick them one-by-one...
>
>In case no.1 does not work, any further ideas of avoiding the 'slave
>work' ?

**Comment by MSe1969** [comment]
I am using "your" TWRP, which we link in our XDA thread. Agree to your kernel approach

**Comment by Micha-Btz** [comment]
I also have successfully encrypt my device, even with adaptable storage. The SELinux should be fixed with latest commit. There are some denies by apps but maybe there are only on my phone depending with apps are installed. 

So the kernel is a little complicated. Since a "easy" merge is not possible I only see the way to go with cherry picking. What do you mean with "List our commit hashes since August 2017" and then compare then to the aicp kernel and only pick the one that are missing?

**Comment by MSe1969** [comment]
With regards to the kernel, it seems we have three possible approaches:

**1. Use AICP Kernel (oreo branch)**
The kernel seems to be fast and stable, but follows more or less Google's and thus also LineageOS' approach to "cherry-pick only the 'security' fixes" instead of merging the kernel maintenance (as long as the kernel is maintained) - so the kernel still shows version 3.4.0 .
Workable approach, but many people question, whether it is a good practice to really cherry-pick security fixes out of the maintenance (they argue that in fact all maintenance commits 'fix' some kernel functionality, so they shouldn't be left out)
Pro: easy, and we don't need to put a lot of effort in
Con: see above

**2. Use SuperLamic's kernel and update it**
SL's kernel seems to contain all Linux kernel commits until EOL plus comprehensive CAF and driver fixes and thus be 'fully up to date until October 2017'. Your testing did no show any issues, but my observations - although so far only 'cosmetical' indicate some issues. SL however uses different device configurations, so maybe it only works out, if we use also SL's device trees together with SL's kernel.
If using SL's device trees makes the kernel 'behave', my idea with the 'list commit hashes' would be: 
a. `git log --pretty=format:"%H %s" --after="2017-08-01" > commits.txt` in our cm-12.1 kernel tree
b. Fetch our kernel into the SL kernel tree
c. Load the commit.txt into an editor and via copy/paste of each of the ~ 150 or so commits try a cherry-pick
Results of each cherry-pick may be:
o empty commit warning (= already applied, so abort cherry-pick)
o cherry-pick applied (cool)
o conflict (ok, analyze...)
Pro: Finally a high quality kernel
Con: huge manual effort and no guaranty of a good result

**3. Use our cm-12.1 kernel base**
You are right, that we can't 'simply use' our kernel - but is it 'only' the def_config command line to be adapted or do we really have to identify the relevant differences to make it work. I admit that I am clueless wrt the necessary steps here.
Pro: our kernel is already in good shape
Con: No idea how easy it is to make it initially work...?

**Comment by Micha-Btz** [comment]
I also made some quick tests. THE AICP kernel has over 4600 commits

> ~/handy/build/cm-14.1/kernel/sony/msm8974
> git log c891ffa5c7eabef047cbab45fccd3c4d66840f40..ef509a31830e6c8620716cb5d3ea5aaeb7cf2cf3 --pretty=oneline | wc -l
> 4610

So not all of these were needed and some of them we have already applied as security fix. So you are right, cherry pick them will make a lot of work. If you cherry-pick an already applied patch, you can abort this with

>  git cherry-pick --abort

so the commit log is nicely clean. 

For me it would be the best to merge the patches from AICP to our kernel, but I don't see a way to get this done without a lot of work. I will try the following:
1. get the commit history of our and of AICP kernel.
2. compare them
3. filter that one we already have applied
4. look through the rest 
5. create the patches by git 
6. see if the patches will added with git am
7. hope it will work :-)

Will see if I can get some magic from bash :-)

**Comment by Micha-Btz** [comment]
I have forked the AICP kernel yesterday, because I have the issue that I can't reboot directly into recovery.
This has worked for me till 7.5 my last build. All other build after that date are behave wrong, the only way to go to recovery is to shutdown the phone and the boot up to recovery.

I will make some test, maybe I can found the reason for this. But I think it would be in general a good idea to have a fork to avoid such kind of problem before we are ready to merge it to our kernel. Since AICP is taking care of Oreo, we probably will run into issues under Nougat.

Will see how many time it take. For the bash magic I have some approach that looks not bad. :-)

From Wednesday on I will travel to the WGT festival until Tuesday.

**Comment by Micha-Btz** [comment]
Every time I have had such a idea I#m impressed was git can handle by itself. So you can cherry-pick a range of commits. 

> git cherry-pick 9e32eaf8c55976c80f8d23662801e4e241373fc8^..b71716e2675a26bc223a14154411f7640191fbdd

I have committed it to the cm-14.1-merge branch. Will see if it work. Maybe we will need some additional commits. Now build test :-)

**Comment by Micha-Btz** [comment]
The stand is, that it not compile. There are some additional patches needed. But this will be fixed after WGT.

**Comment by Micha-Btz** [comment]
I'm not sure it will work this way. After I fix a compile error there are more ones left, sometimes it needs a lot of very old patches. I think there are two options left.
1. merge the aicp kernel
2. use the aicp kernel directly
What do you say?

**Comment by MSe1969** [comment]
Then 2, we can later think about a fork, I've successfully spot-checkef the Oreo branch

**Comment by Micha-Btz** [comment]
What did you mean with "spot-checkef the Oreo branch"?

**Comment by MSe1969** [comment]
Beginning of this month, I have successfully made a build in my cm-14.1 build tree using the below local manifest (please pay special attention to the kernel's revision):
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="cm12-amami/android_device_sony_amami" path="device/sony/amami" />
  <project name="cm12-amami/android_device_sony_rhine-common" path="device/sony/rhine-common" />
  <project name="cm12-amami/android_device_sony_msm8974-common" path="device/sony/msm8974-common" />
  <project name="AICP/kernel_sony_msm8974" path="kernel/sony/msm8974" revision="o8.1" />
  <project name="sonyxperiadev/boringssl-compat" path="external/sony/boringssl-compat" revision="master" />
  <project name="LineageOS/android_device_sony_common" path="device/sony/common" />
  <project name="LineageOS/android_hardware_sony_thermanager" path="hardware/sony/thermanager" />
  <project name="LineageOS/android_hardware_sony_macaddrsetup" path="hardware/sony/macaddrsetup" />
  <project name="LineageOS/android_external_stlport" path="external/stlport" />
  <project name="AICP/proprietary_vendor_sony" path="vendor/sony" revision="n7.1" />
</manifest>
```
With "spot-check", I meant that by using the oreo-branch of the AICP kernel, the phone made a stable impression, but I only made some spot checks (camera, video play, internet browsing, phone call) and restored cm-12.1 afterwards.

**Comment by MSe1969** [comment]
Have created another build with above manifest - all seems to run fine.
However, the logcat is really flooded with below messages:
```
E/qdoverlay(  285): src_rect mdp_rect x=0 y=48 w=720 h=1136
E/qdoverlay(  285): dst_rect mdp_rect x=0 y=48 w=720 h=1136
E/qdoverlay(  285): Bad ov dump:  mdp_overlay z=0 fg=0 alpha=255 mask=-1 flags=0x0 id=-1
E/qdoverlay(  285): src msmfb_img w=736 h=1184 format=13 MDP_RGBA_8888
E/qdoverlay(  285): src_rect mdp_rect x=0 y=48 w=720 h=1136
E/qdoverlay(  285): dst_rect mdp_rect x=0 y=48 w=720 h=1136
E/qdoverlay(  285): Bad ov dump:  mdp_overlay z=0 fg=0 alpha=255 mask=-1 flags=0x0 id=-1
E/qdoverlay(  285): src msmfb_img w=736 h=1184 format=13 MDP_RGBA_8888
```

Need to do a little research on this one...

**Comment by MSe1969** [comment]
Btw, can we delete **android_external_libavc** ? It does not exist for cm-12.1, it has been forked for cm-14.1, but is now two commits behind LineageOS and is not in the manifest - does not seem to make any sense...?

**Comment by Micha-Btz** [comment]
If we don't need  android_external_libavc, then delete this.

The problem with the log spam of  qdoverlay I also have.
https://gist.github.com/Micha-Btz/6bba6a5dc76c65ebc7d4913645459310

The only possible fix I found is https://github.com/LegacyXperia/local_manifests/issues/931#issuecomment-108331450

**Comment by MSe1969** [comment]
I have another idea:
When I tried to disable the HW overlays in dev.settings, the logcat spam immediately disappears, BUT - the android "basic" touch keys ("back", "home", "recent") aren't visible (but still react!), after screen turns black (e.g. after inactivity)

So maybe hahnjo's fixes in our cm-12.1 kernel, which btw. aren't present in the AICP kernel, would help? I will give it a try.

**Comment by Micha-Btz** [comment]
We should decide which way to go. With all builds after the 07.05.2018 i have problems with the screen, after the device is booting the alarm goes on. Locally I have create a branch from the last working state, so it is not possible to use the kernel directly. We should fork it and create our own branch to work with.

Beside the qdoverlay question i have one problem and one minor issue.

1. After flashing a new rom, the device booting successfuly, but it doesn't detect my sd card, which is bad for adaptable storage. After a simple reboot it works as expected.
2. Rebooting to recovery doesn't work. Personally I would say, this has worked before switching selinux to enforce, but I'm not sure.

I will try to debug this. do you have any knowledge how the reboot to recovery mode is working at all? Maybe like the one under linux with forced fsck that just created a file which is used after reboot?

**Comment by MSe1969** [comment]
That confirms my observation - on May 8th a huge merge from a different repo was performed. When I did some analyses yesterday and before, I have noticed, that this merge must have been performed with a kind of "force" strategy, as certain commits are simply repeated and things seem to have been overwritten... - and somehow, the kernel seems to have now some bugs...
I also have the reboot-to-recovery issue: reboot-to-recovery out of the regular system leads to another reboot, but the I can simply press the vol.up key and land in recovery.

I agree we should create an own fork - I did already (MSe1969/android_kernel_sony_msm8974), would you like me to invite you as collaborator or do you prefer to work independently?

**Comment by Micha-Btz** [comment]
I would say, we create a fork to cm-amami. To work independently we can create just branches.
Since git can create branches from a specific commit, we should create a branch before aicp has merged all these strange commits, maybe called cm-14.1 to reflect our state.

I just dislike to maintain two kernels. One thought, since the kernel both are forked from the original cm kernel I suppose that in our cm-12.1 and aicp lp5.1 are nearly equal. Maybe we can merge our kernel in the AICP source for cm-12.1 to just maintain only one kernel? What do you think?

**Comment by MSe1969** [comment]
It is easily possible (I did that already with some other repos) to simply push a new branch from a different repo. Hence we shouldn't mess with our cm-12.1 kernel and leave the 12.1 branches as they are. Instead, we should delete the cm-14 test branches, if we don't need them any longer and simply push one or several new n branches (which we should name cm-14.1*) into it from a local aicp branch. If you want, I can do that - just create a fork on your end, bring it to the initial state, you like and I'll push the branch...

**Comment by Micha-Btz** [comment]
Yes, push the branch would be the fastest and easiest way. If you have time, you can do it, I will not be able to until Sunday.

**Comment by Micha-Btz** [comment]
Thanks for pushing the kernel sources. Did you have success with the overlay patches?

**Comment by MSe1969** [comment]
No, as mentioned - the contents were already present, and even without the last merge-commit, the logcat spam persists.

**Comment by MSe1969** [comment]
Two things: 1. Please purge the cm14 branches, you have created, if you consider them not relevant any longer. If you would like to keep them, I suggest to "rename" them (save under new branch, push and afterwards purge); 2. Github has identified the ACIP kernel as fork of an early cm-11.0 state; I am still a fan of the idea to use our kernel, but I have not yet a good idea how to find the "relevant" commits to adapt the kernel config to run under N. I tried yesterday to simply boot our cm-12.1 kernel via `fastboot boot boot.img` on N, but it simply loops...

**Comment by Micha-Btz** [comment]
I have deleted the don't needed branches and make a clean build on the last stand. And oh miracle the qdoverlay error doesn't appear in the logs, don't know what changes :-) 

Also I have did some research on the boot to recovery problem. The problem is SELinux enforce mode, on permissive it is working. Now it would be a little bit complicated, as far as I have understand, there are two ways how boot to recovery is done.

1. Kernel writes restart reason to specific address and then soft reboots the device, preserving the memory and then bootloader reads the memory address and proceeds to boot recovery.

2. On some devices you can also boot to recovery by writing command to bootloader control block.

I simply don't now how we do this. I tried to reboot and get a log by this in hope that SELinux will complain, but no luck. Ideas?

**Comment by MSe1969** [comment]
That's good news. I can only look next week. As the last merge, which was now removed, was somehow inconsistent (overwrote stuff by repeating commits etc.), maybe the build system did not recognize (during dirty building) to further redo some compiling... as said, can't do a build now to verify. 
No ideas wrt reboot to recovery, we have to maybe search for another bad commit?

**Comment by Micha-Btz** [comment]
I have really bad news. Yesterday my battery was completely empty and the device shut down. I attached the phone to the charger and it load successfully.  It boot up, I inserted my encryption password and then the screen went black and doesn't goes on. Nothing helps. 
A new flash of my build from 30.05.2018 didn't help. The only way to get the screen back was to flash my build from 07.05.2018. After that, I have flashed my build from 30.05.2018 again and the qdoverlay error
came back. 
This is really a show stopper :-(. Since I was not at home, I was not able to get a logcat. I will test this today again. Can you please test this to? Maybe we need some patches from o8.1 too. I will take a look.

**Comment by MSe1969** [comment]
Habe done a clean build and after (dirty) flashing it, same story: black screen after entering decrypt password - have not looked deeper, but restored cm-12.1 because oft June ASB

**Comment by Micha-Btz** [comment]
Have done a build on 1306 and this one is working great. Also the qoverlay problem is not present.
I think there is something strange in the video driver. Sometimes it get to a strange state and causes the trouble. I have ask in #lineage-dev for help but without luck.

Also I get a PN on xda with:
`I tried lineage-14.1-20180613-UNOFFICIAL-amami.zip and lineage-14.1-20180507-UNOFFICIAL-amami.zip. ROM works good but I have troubles with date/time. After every reboot the date resets itself to some date in 1970, latest ROM to 03.08.1970. I didn´t have this problem with LOS14.1 from munjeni and also not with your lineage-14.1-20180425-UNOFFICIAL-amami.zip. Just wanna tell you and may be you can fix this. Thanks!  `
Sounds like a SELinux problem, I will try to get a fix.

**Comment by Micha-Btz** [comment]
So as mentioned in #35 I will stop all effort to get it to a perfect rom. If someone of you will continue with it, please reopen.
